### ISSUE TITLE
Do not exit immediately when GitHub authentication fails

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#225]
For the GitHub App authentication. If the initial requests done by `NewClientPoolInstallations` fail lookout will exit.
We may want to change this, and keep retrying indefinitely, or a number of times. Maybe we could differentiate network problems from authentication errors.

Related to this, `NewClientPoolInstallations` contains `context.TODO`, we probably want to set timeouts.

Context in #211.

**Comment by smacker** [comment]
Could you please explain why do you want to have retry on the app side for this case?

**Comment by smacker** [comment]
On staging kubernetes will try to restart it with increasing timeout forever.

**Comment by dpordomingo** [comment]
Are we implementing this?

Can not be a requirement for the app to be started when all services are ready to be consumed?
Is not useful to rely on the infra to restart the app until the services are ready?

An alternative could be implement our own way to control the retry policy, which failures can be recovered, and which ones cannot; network, database, github, discs...

What is the advantage about keeping the App retrying until everything is solved, compared with relying on the infrastructure to restart the app every time it failed?

**Comment by dpordomingo** [comment]
should we relate this to https://github.com/src-d/lookout/issues/180

**Comment by smacker** [comment]
@dpordomingo I think this issue is "kind of" solved already.

We exit if we can't access github app which I think is very correct. It's very-very broken state of the lookout and it doesn't make much sense to keep running. Nothing will work. If it's a temporary error, ops tools will handle it by restarting in the same way as any other application/component.

About the concern about network errors during getting installation, now we just log error if we can't sync installations and retry again after `installationsSyncInterval`.

**Comment by dpordomingo** [comment]
I agree with @smacker, that matches what I [pointed](https://github.com/src-d/lookout/issues/225#issuecomment-453506458)
Can we close @carlosms ?

**Comment by carlosms** [comment]
ok let's close, now with the installations sync retries the exit on first error goes in line with other fatal errors on start, like DB connection problem.
