### ISSUE TITLE
Docs missing on how to use lookout-sdk CLI with docker-compose

### ISSUE THREAD

**Issue by erizocosmico** [src-d/lookout#386]
After running lookout with docker-compose I wanted to try and see if everything was working. For this, I downloaded `lookout-sdk` and ran the provided command `lookout-sdk review ipv4://localhost:10302`. Of course, since it's running on docker-compose it's not accessible from the outside. Perhaps it should be at least mentioned that "if you're using our docker compose to run things, you will need to use lookout-sdk in this way or that way to connect to services". 
Ports are supposed to be exposed in the docker-compose.yml, but `lookout-sdk` always fails with `Can't connect to analyzer 'localhost:10302': context deadline exceeded`.
Running the container manually with `docker run -p 10302:10302 srcd/lookout-dummy-analyzer` and then executing `lookout-sdk` works, though. 
Some users may choose the path of docker-compose because it's easier to run, but without knowledge about networking inside docker they may hit this wall at some point if no guidance is offered on the README.

**Comment by dpordomingo** [comment]
After revieweing thissue description, and our current docs, I see that when you explained:
>_After running lookout with docker-compose I wanted to try and see if everything was working. For this, I downloaded `lookout-sdk` and ran the provided command `lookout-sdk review ipv4://localhost:10302`._

you came across that problem because of a miscommunication when it was explained the purpose of `lookout-sdk`.

Now, in current [`lookout-sdk docs](https://docs.sourced.tech/lookout/writing-an-analyzer/lookout-sdk) it is said:

>_`lookout-sdk` binary is a simplified version of the `lookoutd` server that works with a local git repository and does not need access to Github. You can think about `lookout-sdk` as a curl-like tool to call an analyzer gRPC endpoint with a `ReviewEvent` or a `PushEvent`, from a local git repository, and send it to an analyzer without accessing GitHub at all._

It is also said now in the [Quickstart section](https://github.com/src-d/lookout/pull/450/commits/02519e6bd1eb7f910d091c11fea24020f93376a1#diff-04c6e90faac2675aa89e2176d2eec7d8R109) that

>_Once it is running, **source{d} Lookout** will start posting the comments returned by `dummy` analyzer into the pull requests opened at GitHub in the repositories that you configured to be watched._

So people should not try to test the whole installation of source{d} Lookout with `lookout-sdk`, but only use it to test a single analyzer.


Please, feel free to reopen this issue if you think we could also explain it better, or in case we could improve it more :dancer:
