### ISSUE TITLE
Propose advanced schema for HistoryDB

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#53]
#35 introduces a simple storage for input (events) and output (comments) of the analysis.

This issue is about proposing additional data model, needed for further operations of lookout server on Github.
 
Things that one might want to persist (not necessarily all in this DB)
 - installations: users, enabling/disabling lookout service on their repositories
 -  [GH App access tokens](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps): YOUR_APP_ID, private key, JWT tokens (10 min expiration), `YOUR_INSTALLATION_ACCESS_TOKEN` (GH API access token, got with JWT, 1h expiration)
 - m.b some state of analyzers?

**Comment by bzz** [comment]
SQL DB changes to integrate:
  - which analyzer posted a comment (so 2 analyzers can post comment on the same line)
  - save PRs/Events separately

**Comment by smacker** [comment]
### Discarded changes

GH installations: it would be nice to store them somewhere later but for now we are fine with keeping it in memory and sync with GH from time to time.

GH tokens: the library we use [keeps tokens in the transport](https://github.com/bradleyfalzon/ghinstallation/blob/master/transport.go#L35) and doesn't allow to change it. It's fine for now. Later when we move to distributed mode we might want to fork it and keep token in some distributed cache to reduce number of calls to github. Similar to [travis](https://github.com/travis-ci/travis-github_apps/blob/master/lib/travis/github_apps.rb#L46)

Analyzers: we don't have any information about analyzer for now beside the config file. I don't think we need to save to db our own configuration.

### Changes

I propose to make as small changes as possible to address current needs:

- extract information about pull request to separate table. We need it to be able to check should we process PR or post comment (they will use different ids). Because we want to be provider agnostic to call the table `review_target`.
- add analyzer name to comment table. I checked the code and we don't really need this field for our code but I see how valuable this field can be in retrospective.

Here is SQL diff. If we are ok with it I'll proceed with PR.

```diff
 CREATE TABLE review_event (
        id uuid NOT NULL PRIMARY KEY,
        status text NOT NULL,
-       provider text NOT NULL,
        internal_id text NOT NULL,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL,
@@ -11,20 +10,20 @@ CREATE TABLE review_event (
        source jsonb NOT NULL,
        merge jsonb NOT NULL,
        configuration jsonb NOT NULL,
-       repository_id bigint NOT NULL,
-       number bigint NOT NULL,
        base jsonb NOT NULL,
-       head jsonb NOT NULL
+       head jsonb NOT NULL,
+       review_id REFERENCES review_target(id),
 );


 CREATE TABLE comment (
        id uuid NOT NULL PRIMARY KEY,
-       review_event_id uuid REFERENCES review_event(id),
+       review_id uuid REFERENCES review_target(id),
        file text NOT NULL,
        line integer NOT NULL,
        text text NOT NULL,
-       confidence bigint NOT NULL
+       confidence bigint NOT NULL,
+       analyzer text NOT NULL,
 );


@@ -42,4 +41,13 @@ CREATE TABLE push_event (
 );


+CREATE TABLE review_target (
+       id uuid NOT NULL PRIMARY KEY,
+       provider text NOT NULL,
+       internal_id text NOT NULL,
+       repository_id bigint NOT NULL,
+       number bigint NOT NULL
+)
```

**Comment by carlosms** [comment]
:+1: from me after some discussion IRL.
Nothing major was discussed, we fixed a relation (comment updated to reflect that), and I'd like to add a comment to make it more clear for others:

When a PR gets new commits pushed, `review_target` will not change. The entry for the PR will be the same. In this case what we will create is a new `review_event` entry, where the `head` will contain the last commit hash to differentiate with older entries.

One thing we didn't discuss and I'm wondering now: should we add [`kallax.Timestamps`](https://github.com/src-d/go-kallax#define-models) to our models? It may be useful in case we want to do some kind of analysis of the DB. Or even debugging.

**Comment by bzz** [comment]
Proposal looks reasonable.

**Comment by smacker** [comment]
@carlosms we already have created_at and updated_at in events. I'll add timestamps to comments and review_target.
