### ISSUE TITLE
Gitlab provider?

### ISSUE THREAD

**Issue by Soullivaneuh** [src-d/lookout#558]
https://github.com/src-d/lookout/tree/master/provider

Did you plan to add provider support for GitLab later?

Would you accept any contribution for this?

Regards.

**Comment by carlosms** [comment]
Yes, we plan to add support for GitLab, but it's not in our short-term roadmap. Any contribution will be welcome, of course.

If you want to work on it, I would recommend to start looking at the GitLab API and see how it maps to the [lookout-sdk structures](https://github.com/src-d/lookout-sdk/blob/master/proto/lookout/sdk/event.proto). You can see the code for [github here](https://github.com/src-d/lookout/blob/master/provider/github/utils.go#L72).

When using the github code as a reference, take into account that the preferred method to authenticate with github is as a GitHub App. Also, we are using polling instead of webhooks to simplify the deployment.

Let us know if you have any questions.

**Comment by Soullivaneuh** [comment]
I just discovered that tool so I will start playing with it first. :wink: 

But if nobody does any contribution for that when I'll need it, I'll take a look for sure! :+1:

**Comment by carlosms** [comment]
:+1: Then I'll close the issue.
If you start working on it and have any questions we can discuss it in the PR or the community slack.
