### ISSUE TITLE
Pass comments generated by `lookout-tool review` call to stdout

### ISSUE THREAD

**Issue by zurk** [src-d/lookout#601]
Right now I need to parse the lookout-tool logs to get Analyzer comments and rely on internal implementation logic (https://github.com/src-d/lookout/blob/master/server/server.go#L559).
For example something like 
`go run cmd/lookout-sdk/*.go review --log-format=json 2>&1 | jq 'select(.msg == "file comment")'` can work.

I think that comments can be interpreted as `lookout-tool review` output and passed to stdout.
It can be in the same log format (JSON/not JSON). 

So in ideal case, I just want to run 
`go run cmd/lookout-sdk/*.go review --log-format=json > comments.json` and get comment per line in JSON format.

**Comment by smacker** [comment]
There is a limitation in go-log: https://github.com/src-d/go-log/issues/11
Go-log doesn't have a maintainer so I just return this issue to TODO.

**Comment by carlosms** [comment]
ping @smola so you are aware of the missing maintainer issue.

**Comment by smola** [comment]
We actually might want to have a JSON poster, alternative to the log one. As we discussed recently, to enable different evaluation and testing use cases.

**Comment by smacker** [comment]
what is the difference between `JSON poster` and log poster with `--format=json`?

**Comment by smola** [comment]
@smacker Logs are written to stdout (no matter the format), while JSON poster would post to stdout. It's kind of differentiating between logging and output. For example: `lookout ... > output.json` would still output logs either in JSON or human readable, but post the meat of the review to the file.

**Comment by smola** [comment]
But it's true that the log poster could be used, just with a different setup (JSON + stdout) than the general logger?

**Comment by smacker** [comment]
We have `LogPoster` struct which implements `Poster` interface.
The constructor of it requires `go-log.Logger` instance. It can be a general one or a separate one.

`main.go` decides what to pass there.
Currently, it's `log.DefaultLogger` but the initial solution for this issue was just to pass `log.New().Output(os.Stdout)` (it would use `DefaultFactory` which is set by `go-cli`)

This way:
- we don't duplicate code to do the same posting
- **results** of analyzer go to stdout always, no matter does user prefer json format or not. Which makes it easy to pipe. For example to test that an analyzer returned N comments you just need to do `./lookout-sdk review | wc -l`. Now this command returns 0 always which doesn't look correct to me.

**Comment by dpordomingo** [comment]
If I'm not wrong, this requirement would be satisfied by https://github.com/src-d/lookout/pull/624
(and `wc -l` would also work)

```bash
$ lookout-sdk review --from HEAD^ 2> log.err | wc -l
5

$ lookout-sdk review --from HEAD^ 2> log.err
{"analyzer-name":"","file":"cmd/lookout-sdk/push.go","text":"The file has increased in 2 lines."}
{"analyzer-name":"","file":"cmd/lookout-sdk/push.go","line":27,"text":"This line exceeded 120 chars."}
{"analyzer-name":"","file":"cmd/lookout-sdk/review.go","text":"The file has increased in 2 lines."}
{"analyzer-name":"","file":"cmd/lookout-sdk/review.go","line":23,"text":"This line exceeded 120 chars."}
{"analyzer-name":"","file":"cmd/sdk-test/bblfsh_test.go","line":146,"text":"This line exceeded 120 chars."}
```

**Comment by smacker** [comment]
Imo by default `lookout-sdk review` should continue print normal response and switch to the json only of the user asks.
